config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get  '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy', as: 'logout'
  get  '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  get '/register', to: 'users#new', as: 'register'

  #resources :votes, only: [:create]

  resources :users, only: [:show, :create, :edit, :update]

  resources :posts, except: :destroy do
    member do
      post :vote  # /posts/3/vote
    end

    # Use 'collection' for routes that don't pertain to a specific post
    # collection do
    #   get 'archives'  # /posts/archives
    # end

    resources :comments, only: [:create] do
      member do
        post :vote  # /posts/3/comments/2/vote
      end
    end

  end

  resources :categories, only: [:new, :create, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(comment_params)

    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was counted'
        else
          flash[:error] = 'You can only vote on a comment once.'
        end

        redirect_to :back
      end

      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<% begin %>
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true),
        method: 'post', remote: true do %>
        <i class='icon-chevron-up'></i>
      <% end %>
      <br/>
    <% end %>
    <div id='comment_<%= comment.id %>_votes'><%= "#{comment.total_votes} votes" %></div>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false),
        method: 'post', remote: true do %>
        <i class='icon-chevron-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class='quiet'>by</span> <%= link_to(comment.user.username, user_path(comment.user)) %>
    <small> on <%= format_time(comment.created_at) %></small>
  </div>
</div>
<% rescue %>
<% end %>

app/views/comments/new.html.erb
<div class='well' />
  <%= form_for @comment do |f| %>
    <div class='control-group' %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 5 %>
    </div>

    <%= f.submit('Post Comment', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %> votes');
<% else %>
  alert('You can only vote on a comment once.');
<% end %>