config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get  '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy', as: 'logout'
  get  '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  get '/register', to: 'users#new', as: 'register'

  #resources :votes, only: [:create]

  resources :users, only: [:show, :create, :edit, :update]

  resources :posts, except: :destroy do
    member do
      post :vote  # /posts/3/vote
    end

    # Use 'collection' for routes that don't pertain to a specific post
    # collection do
    #   get 'archives'  # /posts/archives
    # end

    resources :comments, only: [:create] do
      member do
        post :vote  # /posts/3/comments/2/vote
      end
    end

  end

  resources :categories, only: [:new, :create, :show]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  # Simpler relationship declaration uses the standard naming
  #  conventions to relate things together
  #belongs_to :user
  # Could use the more explicit form for the relationship
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  # Required for Sluggable Module
  sluggable_column :title

  # def slug_value
  #   self.title
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator_or_above, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
    respond_to do |format|
      format.html {}
      format.json { render json: @posts }
      format.xml  { render xml:  @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html {}
      format.json { render json: sanitize_for_external_api(@post) }
      format.xml  { render xml: sanitize_for_external_api(@post)  }
    end

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Post successfully created'
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'The post was updated'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote was counted.'
        else
          flash[:error] = 'You can only vote on a post once.'
        end

        redirect_to :back
      end

      format.js do
        render :vote
      end

    end

  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def find_post
    @post = Post.find_by(slug: params[:id])
  end

  def vote_params
    params.require(:post)
  end

  def require_creator_or_above
    access_denied('You cannot edit that.') unless @post.creator == current_user or
      current_user.admin?
  end

  def sanitize_for_external_api(post)
    post_attrs = post.attributes
    post_attrs["username"] = post.creator.username
    sanitized_attrs = post_attrs.select{ |key, val| not ['id', 'user_id'].include?(key) }
  end

end

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors:</h5>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-chevron-up'></i>
      <% end %>
      <br/>
    <% end %>
    <div id='post_<%= post.slug %>_votes'><%= post.total_votes %> votes</div>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-chevron-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by </span><%= link_to(post.creator.username, user_path(post.creator)) %>
      <small> on <%= format_time(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>

    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'shared/errors', object: @post %>

<%= render 'post_form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create Post' %>

<%= render 'shared/errors', object: @post %>

<%= render 'post_form' %>

app/views/posts/show.html.erb
<% if current_user == @post.creator or (logged_in? and current_user.admin?) %>
  <p class='pull-right'>
    [<%= link_to 'Edit this post', edit_post_path(@post) %>]
  </p>
<% end %>
<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: link_to(@post.title, fix_url(@post.url)) %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <div class='well' />
    <%= form_for [@post, @comment] do |f| %>
      <%= render 'shared/errors', object: @comment %>
      <div class='control-group' %>
        <%= f.label :body, 'Leave a comment:' %>
        <%= f.text_area :body, rows: 3, class: 'span4' %>
      </div>
      <%= f.submit('Post Comment', class: 'btn btn-primary') %>
    <% end %>
  </div>
<% end %>

<h4>Comments:</h4>

<% @post.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html('<%= @post.total_votes %> votes');
<% else %>
  alert('You can only vote on a post once.');
<% end %>